### ISSUE TITLE
Making Python file readable

### ISSUE THREAD

**Issue by ziadab** [Praudyogikee-org/Anonybox#1]
Can u guys separate the file of python side and not stack all code in one file 
Because I find it hard to contribute to your project

Thanks UwU

**Comment by qarqoush** [comment]
@IslaIDK  This issue will be forwarded to isla

**Comment by IslaIDK** [comment]
alright uwu

**Comment by ziadab** [comment]
Thanks UwU

**Comment by qarqoush** [comment]
Feb 25. 2020.
Python files are separated.
