### ISSUE TITLE
Fixed Initialization Vector in AES.py

### ISSUE THREAD

**Issue by 0xOFFSET** [Praudyogikee-org/Anonybox#4]
Why not giving it a random value when each new message gets encrypted ?

**Comment by qarqoush** [comment]
Default setting is: Random Value for each connection.
Anyway, @IslaIDK is responsible for the python side.

**Comment by IslaIDK** [comment]
Giving it a random value won't change anything also to decrypt the message the user should be aware about the value that was used in this case we should send the value too in my view it's not safe, We can let the user to change the value any time they needs is much better
